apiVersion: v1
name: healthcheck
description: healthcheck chart that runs on kubernetes
version: 1.0.1
keywords:
  - healthcheck
  - kubernetes
home: https://gitlab.dell.com/business/services/sdst/tsb/healthcheck