---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: {{ .Chart.Version }}
      name: diagnostics
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ .Chart.Name }}
      template:
        metadata:
          labels:
            provider: fabric8
            app: {{ .Chart.Name }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: {{ .Release.Name | quote }}
            heritage: {{ .Release.Service | quote }}
            version: 1.0.2
        spec:
          containers:
            - image: "{{ .Values.diagnostics.image.name }}:{{ .Values.diagnostics.image.tag }}"
              imagePullPolicy: {{ .Values.diagnostics.image.pullPolicy }}
              name: diagnostics
              securityContext:
                privileged: false