---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: {{ .Chart.Version }}
      name: healthcheck
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ .Chart.Name }}
      template:
        metadata:
          labels:
            provider: fabric8
            app: {{ .Chart.Name }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: {{ .Release.Name | quote }}
            heritage: {{ .Release.Service | quote }}
            version: 1.0.2
        spec:
          containers:
            - image: "{{ .Values.healthcheck.image.name }}:{{ .Values.healthcheck.image.tag }}"
              imagePullPolicy: {{ .Values.healthcheck.image.pullPolicy }}
#              livenessProbe:
#                initialDelaySeconds: 60
#                tcpSocket:
#                  port: 8090
              name: healthcheck
#              readinessProbe:
#                httpGet:
#                  path: /healthcheck/api/fetchhealth
#                  port: 8090
#                initialDelaySeconds: 5
              securityContext:
                privileged: false