---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        fabric8.io/ingress.annotations: |-
          ingress.kubernetes.io/force-ssl-redirect: false
          kubernetes.io/ingress.class: {{ .Values.healthcheck.service.ingressClass }}
      labels:
        expose: "true"
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: 1.0.2
      name: healthcheck
    spec:
      ports:
        - name: http
          port: 8090
          protocol: TCP
          targetPort: 8090
      selector:
        app: {{ .Chart.Name }}