---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: {{ .Chart.Version }}
      name: edgestrategypoc
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ .Chart.Name }}
      template:
        metadata:
          labels:
            provider: fabric8
            app: {{ .Chart.Name }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: {{ .Release.Name | quote }}
            heritage: {{ .Release.Service | quote }}
            version: 1.0.2
        spec:
          containers:
            - image: "{{ .Values.edgestrategypoc.image.name }}:{{ .Values.edgestrategypoc.image.tag }}"
              imagePullPolicy: {{ .Values.edgestrategypoc.image.pullPolicy }}
              env:
                - name: DIAGNOSTICS_URL
                  value: http://diagnostics:8060
                - name: INVENTORY_URL
                  value: http://inventory:8070
#              livenessProbe:
#                initialDelaySeconds: 60
#                tcpSocket:
#                  port: 8080
              name: edgestrategypoc
#              readinessProbe:
#                httpGet:
#                  path: /api/inventory
#                  port: 8070
#                initialDelaySeconds: 5
              securityContext:
                privileged: false