---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        version: {{ .Chart.Version }}
      name: inventory
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: {{ .Chart.Name }}
      template:
        metadata:
          labels:
            provider: fabric8
            app: {{ .Chart.Name }}
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            release: {{ .Release.Name | quote }}
            heritage: {{ .Release.Service | quote }}
            version: 1.0.2
        spec:
          containers:
            - image: "{{ .Values.inventory.image.name }}:{{ .Values.inventory.image.tag }}"
              imagePullPolicy: {{ .Values.inventory.image.pullPolicy }}
              env:
                - name: HEALTH_CHECK_URL
                  value: http://healthcheck:8090
#              livenessProbe:
#                initialDelaySeconds: 60
#                tcpSocket:
#                  port: 8080
              name: inventory
#              readinessProbe:
#                httpGet:
#                  path: /inventory/api/fetchinventory
#                  port: 8080
#                initialDelaySeconds: 5
              securityContext:
                privileged: false